### ISSUE TITLE
fails for single and remote url

### ISSUE THREAD

**Issue by aaronspring** [edjdavid/intake-excel#1]
I tried to open just one single excel file but this doesnt work, but it works in pandas. Do you see a way to fix that?

```python
url='http://cdiac.ess-dive.lbl.gov/ftp/Global_Carbon_Project/Global_Carbon_Budget_2016_v1.0.xlsx'
item = intake.open_excel(url)
item = intake_excel.ExcelSource(url)
IndexError: list index out of range

import pandas as pd
pd.read_excel(url) #works
```

**Comment by edjdavid** [comment]
I'll take a look at opening remote excel files. It's working when the files are local.

**Comment by aaronspring** [comment]
thanks this now works great.
```
item = intake_excel.ExcelSource(url,excel_kwargs=dict(sheet_name='Global Carbon Budget',header=21,index_col='Year'))
item.read()
```

**Comment by aaronspring** [comment]
@edjdavid if you are interested, you could probably migrate this package into the `intake` organization https://github.com/intake. probably more people will see and use it then. ping @martindurant

**Comment by martindurant** [comment]
Note that pandas.read_excel does handle remote URLs now via fsspec

This package could do with being posted on pypi and conda-forge, but I am not opposed to hosting it in the intake org, if it makes a difference.

Probably a more direct way to get noticed is to list at https://intake.readthedocs.io/en/latest/plugin-directory.html

**Comment by edjdavid** [comment]
will submit this to the plugin list, pypi, and conda-forge. thanks!
